AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: user
            AttributeDefinitions:
                -   AttributeName: Email
                    AttributeType: S
            KeySchema:
                -   AttributeName: Email
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1