AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    UserTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: user
            AttributeDefinitions:
                -   AttributeName: Id
                    AttributeType: S
                -   AttributeName: Email
                    AttributeType: S
            KeySchema:
                -   AttributeName: Id
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            GlobalSecondaryIndexes:
                -   ContributorInsightsSpecification:
                        Enabled: true
                    IndexName: "Email-Index"
                    KeySchema:
                        -   AttributeName: Email
                            KeyType: HASH
                    Projection:
                        ProjectionType: ALL
                    ProvisionedThroughput:
                        ReadCapacityUnits: 1
                        WriteCapacityUnits: 1
    DeviceTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: device
            AttributeDefinitions:
                -   AttributeName: Id
                    AttributeType: S
                -   AttributeName: RefreshToken
                    AttributeType: S
            KeySchema:
                -   AttributeName: Id
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            GlobalSecondaryIndexes:
                -   ContributorInsightsSpecification:
                        Enabled: true
                    IndexName: "RefreshToken-Index"
                    KeySchema:
                        -   AttributeName: RefreshToken
                            KeyType: HASH
                    Projection:
                        ProjectionType: ALL
                    ProvisionedThroughput:
                        ReadCapacityUnits: 1
                        WriteCapacityUnits: 1
    Cipher:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: cipher
            AttributeDefinitions:
                -   AttributeName: Id
                    AttributeType: S
                -   AttributeName: UserId
                    AttributeType: S
            KeySchema:
                -   AttributeName: UserId
                    KeyType: HASH
                -   AttributeName: Id
                    KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
#            GlobalSecondaryIndexes:
#                - ContributorInsightsSpecification:
#                      Enabled: true
#                  IndexName: "RefreshToken-Index"
#                  KeySchema:
#                      - AttributeName: RefreshToken
#                        KeyType: HASH
#                  Projection:
#                      ProjectionType: ALL
#                  ProvisionedThroughput:
#                      ReadCapacityUnits: 1
#                      WriteCapacityUnits: 1