AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    KotWardenHttpApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            StageName: $default
            DefaultRouteSettings:
                ThrottlingBurstLimit: 5
                ThrottlingRateLimit: 10
    KotWardenFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: .
            FunctionName: !Sub KotWarden-Handle
            Handler: com.ivyxjc.kotwarden.Server::handleRequest
            Runtime: java11
            Timeout: 15
            Tracing: Active
            Architectures:
                - x86_64
            MemorySize: 832
            Policies:
                - AmazonDynamoDBFullAccess
            Events:
                ApiEvent:
                    ApiId: !Ref 'KotWardenHttpApi'
                    Type: HttpApi
                    Properties:
                        Method: ANY
                        Path: /{proxy+}
                        TimeoutInMillis: 5000